/*
 * Export the demo's FHIR resources (generated by the JS data layer) to
 * /tmp/apix-res/ so the official HL7 validator can check them. Used by
 * validation/validate.sh.
 */
const path = require('path');
const fs = require('fs');
const ROOT = path.join(__dirname, '..');

global.window = global;
global.CustomEvent = class extends Event { constructor(t, i) { super(t); this.detail = i && i.detail; } };

['highlight', 'codesystems', 'terminology', 'config', 'fhir-server', 'client', 'seed', 'pqi', 'scenario', 'store'].forEach(function (f) {
  eval(fs.readFileSync(path.join(ROOT, 'js', f + '.js'), 'utf8'));
});

APIX.pqi.normalize();
const OUT = '/tmp/apix-res';
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const w = (n, o) => fs.writeFileSync(path.join(OUT, n + '.json'), JSON.stringify(o, null, 2));

w('Bundle-pqi', APIX.pqi.bundle);
w('Organization-applicant', APIX.seed.applicant);
w('MedicinalProductDefinition', APIX.seed.product);
w('Endpoint', APIX.seed.endpoint);
w('SubscriptionTopic', APIX.seed.topicStatus);
w('Subscription', APIX.seed.subscription);

// The store's connect/submit/subscribe are now async (uniform with live mode);
// await the flow before reading the server-returned Task back out.
(async function () {
  await APIX.store.connect();
  await APIX.store.submit();
  await APIX.store.subscribe();
  // ONE payload: the submission Task carries exactly one input — the single
  // structured drug-product-specification DocumentReference (→ PQI Bundle Binary).
  if (APIX.store.task.input.length !== 1) {
    throw new Error('Expected Task.input.length === 1, got ' + APIX.store.task.input.length);
  }
  w('Task', APIX.store.task);
  w('DocumentReference', APIX.store.get('DocumentReference/docref-spec-fhir'));
  // A representative audit Provenance (base R5 — no APIX profile) so the
  // official validator confirms it is valid FHIR R5.
  w('Provenance', APIX.store.provenance[0]);

  // 9 resources: Bundle-pqi, Organization, MedicinalProductDefinition, Endpoint,
  // SubscriptionTopic, Subscription, Task, the single spec DocumentReference, Provenance.
  console.log('Exported ' + fs.readdirSync(OUT).length + ' resources to ' + OUT);
})().catch(function (e) { console.error(e); process.exit(1); });
